import argparse
import json
import os
import re
import sys
import time
from datetime import datetime
from html import unescape

import feedparser
import requests

# ==========================================
# DEFAULT CONFIGURATION
# ==========================================
DEFAULT_SUBREDDIT = "devops"
DEFAULT_POST_LIMIT = 100
DEFAULT_COMMENTS_PER_POST = 5
DEFAULT_SORT = "new"
SERVER_URL = "http://127.0.0.1:8080/v1/chat/completions"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 DevPainPointMiner/2.0",
    "Accept": "*/*",
}


def strip_html(text: str) -> str:
    """Remove HTML tags and decode HTML entities."""
    clean = re.sub(r"<[^>]+>", " ", text)
    clean = unescape(clean)
    clean = re.sub(r"\s+", " ", clean).strip()
    return clean


def check_server_ready():
    """Waits for local DeepSeek-R1 GPU server (llama-server) to be ready."""
    print("[*] Checking local DeepSeek-R1 GPU server status (http://127.0.0.1:8080)...")
    for _ in range(15):
        try:
            res = requests.get("http://127.0.0.1:8080/health", timeout=3)
            if res.status_code == 200:
                print("[+] Local DeepSeek-R1 GPU server is READY!\n")
                return True
        except Exception:
            pass
        time.sleep(2)
    print("[WARNING] GPU server health check timed out. Proceeding...")
    return False


def extract_pain_point_with_deepseek(text: str) -> dict:
    """
    Uses local DeepSeek-R1 model on GPU to analyze developer posts/comments
    and extract actionable developer pain points and SaaS startup opportunities.
    """
    if not text or not text.strip():
        return {
            "has_pain_point": False,
            "pain_category": "None",
            "problem_statement": "Empty text",
            "severity": "Minor",
            "startup_opportunity": "None",
            "reasoning": "",
        }

    truncated_text = text.strip()[:1200]

    system_prompt = (
        "You are an expert SaaS Venture Capitalist and Developer Tooling Researcher. "
        "Your task is to analyze developer discussions from Reddit to identify real developer pain points, "
        "frustrations, unfulfilled needs, and potential SaaS/DevTool startup opportunities.\n\n"
        "Respond STRICTLY in JSON format with the following 5 keys:\n"
        '1. "has_pain_point": true if the text expresses a clear problem, frustration, bug, or missing capability; false if purely informational/news.\n'
        '2. "pain_category": a short 2-4 word category (e.g. "GPU Memory Leaks", "Deployment & CI/CD", "Boilerplate & Config", "Monitoring & Observability", "API & Interop", "Performance & Latency").\n'
        '3. "problem_statement": a 1-2 sentence concise description of what the developer is struggling with.\n'
        '4. "severity": one of "Critical", "Moderate", or "Minor".\n'
        '5. "startup_opportunity": a 1-2 sentence SaaS product or open-source tool concept that could solve this pain point.'
    )

    payload = {
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Analyze this developer text for pain points and startup ideas:\n\"\"\"{truncated_text}\"\"\""},
        ],
        "temperature": 0.2,
        "max_tokens": 512,
    }

    try:
        response = requests.post(SERVER_URL, json=payload, timeout=60)
        if response.status_code != 200:
            return {
                "has_pain_point": False,
                "pain_category": "Error",
                "problem_statement": f"HTTP {response.status_code} from local server",
                "severity": "Minor",
                "startup_opportunity": "None",
                "reasoning": "",
            }

        res_data = response.json()
        output_text = res_data["choices"][0]["message"]["content"].strip()

        # Parse <think>...</think> reasoning generated by DeepSeek R1
        think_reasoning = ""
        final_answer = output_text

        if "<think>" in output_text and "</think>" in output_text:
            parts = output_text.split("</think>")
            think_reasoning = parts[0].replace("<think>", "").strip()
            final_answer = parts[1].strip()
        elif "<think>" in output_text:
            think_reasoning = output_text.replace("<think>", "").strip()

        # Clean JSON markdown if present
        if "```json" in final_answer:
            final_answer = final_answer.split("```json")[1].split("```")[0].strip()
        elif "```" in final_answer:
            final_answer = final_answer.split("```")[1].split("```")[0].strip()

        # Regex search for JSON block
        json_match = re.search(r"\{.*\}", final_answer, re.DOTALL)
        if json_match:
            try:
                parsed = json.loads(json_match.group(0))
                return {
                    "has_pain_point": bool(parsed.get("has_pain_point", False)),
                    "pain_category": parsed.get("pain_category", "General Developer Need"),
                    "problem_statement": parsed.get("problem_statement", final_answer),
                    "severity": parsed.get("severity", "Moderate"),
                    "startup_opportunity": parsed.get("startup_opportunity", "N/A"),
                    "reasoning": think_reasoning,
                }
            except json.JSONDecodeError:
                pass

        # Fallback if text isn't strict JSON
        lower_ans = final_answer.lower()
        has_pain = any(w in lower_ans for w in ["error", "fail", "issue", "problem", "bug", "crash", "stuck", "slow", "hard", "leak", "help"])
        return {
            "has_pain_point": has_pain,
            "pain_category": "Developer Usability & Infrastructure",
            "problem_statement": final_answer[:300],
            "severity": "Moderate" if has_pain else "Minor",
            "startup_opportunity": "Automated devtool/service to streamline this workflow.",
            "reasoning": think_reasoning,
        }

    except Exception as e:
        return {
            "has_pain_point": False,
            "pain_category": "Error",
            "problem_statement": str(e),
            "severity": "Minor",
            "startup_opportunity": "None",
            "reasoning": "",
        }


def fetch_subreddit_rss(subreddit: str, sort: str = "new", limit: int = 100) -> list:
    """Fetches up to limit posts from Reddit's public RSS feed."""
    url = f"https://www.reddit.com/r/{subreddit}/{sort}/.rss?limit={limit}"
    print(f"[*] Fetching RSS feed from: {url}")

    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        if response.status_code != 200:
            print(f"[WARNING] Reddit returned HTTP {response.status_code}.")
            return []

        feed = feedparser.parse(response.text)
        posts = []

        for entry in feed.entries[:limit]:
            title = entry.get("title", "")
            selftext = strip_html(entry.get("summary", ""))
            link = entry.get("link", "")
            author = entry.get("author", "N/A")
            if author.startswith("/u/"):
                author = author[3:]

            posts.append({
                "post_id": entry.get("id", ""),
                "title": title,
                "author": author,
                "url": link,
                "selftext": selftext,
                "permalink": link.replace("https://www.reddit.com", ""),
            })

        return posts
    except Exception as e:
        print(f"[WARNING] Exception fetching RSS: {e}")
        return []


def fetch_post_comments_rss(permalink: str, limit: int = 5) -> list:
    """Fetches top comments for a post via RSS."""
    if not permalink or permalink.startswith("/r/vllm/comments/vllm_"):
        return []

    url = f"https://www.reddit.com{permalink}.rss"
    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        if response.status_code != 200:
            return []

        feed = feedparser.parse(response.text)
        comments = []

        for entry in feed.entries[1:]:
            body = strip_html(entry.get("summary", ""))
            author = entry.get("author", "N/A")
            if author.startswith("/u/"):
                author = author[3:]

            if body and author != "AutoModerator":
                comments.append({
                    "comment_id": entry.get("id", ""),
                    "author": author,
                    "body": body,
                })
                if len(comments) >= limit:
                    break

        return comments
    except Exception:
        return []


def generate_markdown_report(subreddit: str, pain_points: list, summary_stats: dict, output_file: str):
    """Generates a professional Markdown startup opportunities report."""
    md_content = f"# 🚀 Startup Opportunity & Developer Pain Point Report\n\n"
    md_content += f"- **Target Subreddit:** `r/{subreddit}`\n"
    md_content += f"- **Analyzed At:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    md_content += f"- **Model Used:** DeepSeek-R1-Distill-Qwen-7B (Local GPU CUDA Engine)\n"
    md_content += f"- **Total Discussions Analyzed:** {summary_stats['total_analyzed']}\n"
    md_content += f"- **Pain Points Identified:** {len(pain_points)} ({len(pain_points)/max(summary_stats['total_analyzed'],1):.0%})\n\n"

    md_content += "---\n\n## 📊 Category Breakdown\n\n"
    md_content += "| Pain Point Category | Occurrences | High-Severity Ratio |\n"
    md_content += "|---|---|---|\n"

    category_counts = {}
    for item in pain_points:
        cat = item["analysis"]["pain_category"]
        category_counts[cat] = category_counts.get(cat, 0) + 1

    for cat, count in sorted(category_counts.items(), key=lambda x: x[1], reverse=True):
        md_content += f"| **{cat}** | {count} | {round(count/len(pain_points)*100)}% |\n"

    md_content += "\n---\n\n## 💡 Key Developer Pain Points & Validated Startup Ideas\n\n"

    for idx, item in enumerate(pain_points, 1):
        analysis = item["analysis"]
        title_safe = item['title'].encode("ascii", "ignore").decode("ascii")
        md_content += f"### {idx}. [{analysis['severity'].upper()}] {analysis['pain_category']}: {title_safe}\n"
        md_content += f"- **Author:** `u/{item['author']}` | [Reddit Post Link]({item['url']})\n"
        md_content += f"- **Developer Problem:** {analysis['problem_statement']}\n"
        md_content += f"- **💡 Startup Opportunity:** **{analysis['startup_opportunity']}**\n"
        if analysis.get("reasoning"):
            md_content += f"- **🧠 DeepSeek-R1 Thought Process (`<think>`):** *\"{analysis['reasoning'][:200]}...\"*\n"
        md_content += "\n"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"\n[+] Markdown Startup Opportunity Report saved to:\n    {output_file}")


def main():
    parser = argparse.ArgumentParser(description="Mine developer pain points and SaaS startup opportunities from Reddit using local DeepSeek-R1 GPU.")
    parser.add_argument("--subreddit", type=str, default=DEFAULT_SUBREDDIT, help="Target subreddit (e.g. devops, LocalLLaMA, LangChain)")
    parser.add_argument("--limit", type=int, default=DEFAULT_POST_LIMIT, help="Number of posts to fetch (default: 100)")
    parser.add_argument("--comments", type=int, default=DEFAULT_COMMENTS_PER_POST, help="Comments per post to analyze (default: 5)")
    parser.add_argument("--sort", type=str, default=DEFAULT_SORT, help="Reddit sort order: new, hot, top (default: new)")
    args = parser.parse_args()

    subreddit = args.subreddit
    limit = args.limit
    comments_limit = args.comments
    sort = args.sort

    print(f"[*] Starting Developer Pain Point & Startup Miner on r/{subreddit} ({limit} latest posts)...\n")

    check_server_ready()

    posts = fetch_subreddit_rss(subreddit, sort=sort, limit=limit)

    if not posts:
        print("[ERROR] No posts found.")
        return

    results = []
    pain_points_found = []
    summary_stats = {"total_analyzed": 0, "pain_points": 0}

    print(f"[+] Found {len(posts)} posts. Extracting developer pain points using DeepSeek-R1 on GPU...")
    print("=" * 80)

    for i, post in enumerate(posts, 1):
        title_safe = post['title'].encode("ascii", "ignore").decode("ascii")
        print(f"\n[{i}/{len(posts)}] Analyzing Discussion: {title_safe[:80]}")
        print(f"  Author: u/{post['author']}")

        post_text = f"Title: {post['title']}\nSelftext: {post['selftext']}"
        analysis = extract_pain_point_with_deepseek(post_text)
        summary_stats["total_analyzed"] += 1

        if analysis.get("has_pain_point"):
            summary_stats["pain_points"] += 1
            print(f"  -> [PAIN POINT DETECTED] [{analysis.get('severity')}] Category: {analysis.get('pain_category')}")
            print(f"  -> Problem   : {analysis.get('problem_statement')}")
            print(f"  -> SaaS Idea : {analysis.get('startup_opportunity')}")

            pain_points_found.append({
                "type": "post",
                "title": post["title"],
                "author": post["author"],
                "url": post["url"],
                "analysis": analysis,
            })
        else:
            print(f"  -> Info / News (No critical pain point)")

        time.sleep(0.1)
        top_comments = fetch_post_comments_rss(post["permalink"], limit=comments_limit)

        comments_analysis = []
        if top_comments:
            print(f"  --- Analyzing Top {len(top_comments)} Comments ---")
            for c_idx, comment in enumerate(top_comments, 1):
                c_analysis = extract_pain_point_with_deepseek(comment["body"])
                summary_stats["total_analyzed"] += 1

                body_preview = comment["body"][:75].replace("\n", " ").encode("ascii", "ignore").decode("ascii")

                if c_analysis.get("has_pain_point"):
                    summary_stats["pain_points"] += 1
                    print(f'    Comment [{c_idx}] by u/{comment["author"]}: "{body_preview}..."')
                    print(f"      -> [PAIN POINT]: [{c_analysis.get('severity')}] {c_analysis.get('problem_statement')}")
                    print(f"      -> SaaS Idea: {c_analysis.get('startup_opportunity')}")

                    pain_points_found.append({
                        "type": "comment",
                        "title": f"Comment on: {post['title']}",
                        "author": comment["author"],
                        "url": post["url"],
                        "analysis": c_analysis,
                    })

                comments_analysis.append({
                    "comment_id": comment["comment_id"],
                    "author": comment["author"],
                    "body": comment["body"],
                    "analysis": c_analysis,
                })

        print("=" * 80)

        post["analysis"] = analysis
        post["comments"] = comments_analysis
        results.append(post)

        # Save live JSON progress
        live_filename = f"deepseek_r1_painpoints_live.json"
        live_path = os.path.join(os.path.dirname(__file__), live_filename)
        with open(live_path, "w", encoding="utf-8") as f:
            json.dump({
                "subreddit": subreddit,
                "model": "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M",
                "status": f"Processing post {i}/{len(posts)}",
                "analyzed_at": datetime.now().isoformat(),
                "summary": summary_stats,
                "pain_points_found": pain_points_found,
                "posts": results,
            }, f, indent=2, ensure_ascii=False)

    # Output filenames
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(os.path.join(os.path.dirname(__file__), "reports"), exist_ok=True)
    json_output_file = os.path.join(os.path.dirname(__file__), "reports", f"deepseek_r1_painpoints_r_{subreddit}_{timestamp_str}.json")
    md_output_file = os.path.join(os.path.dirname(__file__), "reports", f"startup_opportunities_r_{subreddit}_{timestamp_str}.md")

    # Write final JSON
    with open(json_output_file, "w", encoding="utf-8") as f:
        json.dump({
            "subreddit": subreddit,
            "model": "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M",
            "analyzed_at": datetime.now().isoformat(),
            "summary": summary_stats,
            "pain_points_found": pain_points_found,
            "posts": results,
        }, f, indent=2, ensure_ascii=False)

    # Write final Markdown report
    generate_markdown_report(subreddit, pain_points_found, summary_stats, md_output_file)

    print(f"\n[+] Analysis complete! Summary report saved to:\n    JSON: {json_output_file}\n    MD:   {md_output_file}")


if __name__ == "__main__":
    main()
