concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint workflows
    permissions:
      contents: read # required to check out the repository
    uses: praw-dev/.github/.github/workflows/lint.yml@68c4e3402dc6c829ac9a1a787a663baabd21388b # v1.7.0
name: Lint workflows
on:
  pull_request:
  push:
    branches: ["main"]
permissions: {}
