jobs:
  set_active_docs:
    name: Set Active Docs
    secrets:
      READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
    uses: praw-dev/.github/.github/workflows/set_active_docs.yml@68c4e3402dc6c829ac9a1a787a663baabd21388b # v1.7.0
name: Set Active Docs
on:
  release:
    types: [ published ]
permissions:
  contents: read
