jobs:
  tag_release:
    name: Tag Release
    permissions:
      contents: write # required to push the release tag
    uses: praw-dev/.github/.github/workflows/tag_release.yml@68c4e3402dc6c829ac9a1a787a663baabd21388b # v1.7.0
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions: {}
